#!/bin/sh

CWD=`pwd`
NCPU=`grep -c processor /proc/cpuinfo`
PROGNAME="setup-environment"

if [ "$(whoami)" = "root" ]; then
    echo "Error: do not run as root. Exiting..."
    exit
fi

clean_up()
{
    unset EULA LIST_MACHINES VALID_MACHINE
    unset NCPU CWD TEMPLATES SHORTOPTS LONGOPTS ARGS PROGNAME
    unset generated_config updated
    unset MACHINE SDKMACHINE DISTRO OEROOT
}

OEROOT=sources/poky

cd $OEROOT
mkdir -p $CWD/$1
. ./oe-init-build-env $CWD/$1 > /dev/null

if [ ! -e conf/local.conf ]; then
    echo "Error: run script fail..."
    clean_up && exit
fi

if [ ! -e conf/local.conf.sample ]; then
    mv conf/local.conf conf/local.conf.sample

    cp $CWD/sources/base/conf/local.conf.$DISTRO-$MACHINE conf/local.conf
    cp $CWD/sources/base/conf/bblayers.conf.$DISTRO-$MACHINE conf/bblayers.conf

    sed -e "s,BSPDIR :=.*,BSPDIR := \"$CWD\",g" -i conf/local.conf
    sed -e "s,BSPDIR :=.*,BSPDIR := \"$CWD\",g" -i conf/bblayers.conf

    echo "Complete your configuration:
        DISTRO    := $DISTRO
        MACHINE   := $MACHINE
        BITBAKE   := $2
        BUILD_DIR := $CWD/$1"

else
    echo "Your build environment has been configured with:
        DISTRO    := $DISTRO
        MACHINE   := $MACHINE
        BITBAKE   := $2
        BUILD_DIR := $CWD/$1"
    echo "Your configuration files at $2 have not been touched."
fi

bitbake $2
cd $CWD
clean_up
